### ISSUE TITLE
CreateAction with transaction

### ISSUE THREAD

**Issue by jkrajinovic** [tunecino/yii2-nested-rest#7]
Hi, great work.

Question: Should CrateAction be wrapped within try catch and with transaction?

If nested model passes validation, but model for junction table not, the main
model still gets saved with junction table model validation errors.

Thanks.

**Comment by tunecino** [comment]
Thanks.

> If nested model passes validation, but model for junction table not, the main
> model still gets saved with junction table model validation errors.

Validating junction table data is easy you just need to use [via()](http://www.yiiframework.com/doc-2.0/yii-db-activerelationtrait.html#via%28%29-detail) instead of `viaTable()` when defining relations inside your models as shown in [Yii docs](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#junction-table). The script should load the junction related model in that case and handle its validation properly as defined in its `rules()` method before saving it. related extension code could be seen [here](https://github.com/tunecino/yii2-nested-rest/blob/master/src/CreateAction.php#L80_L102). 

> Should CrateAction be wrapped within try catch

Only framework's native methods like [yii\db\BaseActiveRecord::link()](https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1235) and `yii\db\BaseActiveRecord::save()` are used here. so I'd expect those built-in methods to do their job correctly. If try catch are required at some point they should be already using them.

> with transaction?

Transactions are what I'd like to implement too in my own app but as they where not implemented by default in the [framework's built-in actions](https://github.com/yiisoft/yii2/tree/master/framework/rest) I decided to just do the same. I don't know if all the databases supported by Yii are supporting Transactions specially the NoSQL ones. When you need Transactions and your DB supports it I think it is better to create your own version of the `CrateAction` and include it within your controller instead of the original one.

**Comment by jkrajinovic** [comment]
Thanks for the thorough explanation.

Did think of creating my own CreateAction but just wanted to check if perhaps something similar is going to be implemented. I agree with your explanation. Try catch was only proposed to rollback transaction.

I used via already, everything validates correctly, except I want to either save the model and junction model together or not save them at all.

Thanks, you addressed my concerns.

Best regards
